src/bastion/crates/core/src/approval.rs
use crate::{audit::AuditChain, types::ApprovalTicket};
use std::collections::HashMap;
use std::sync::Arc;
use sha2::Sha256;
use chrono::Utc;

/// Represents a single approval ticket with the metadata to be signed.
#[derive(Debug)]
pub struct ApprovalTicket {
    pub session_id: String,
    pub action_id: String,
    /// The HMAC signature generated by this specific request.
    pub signature: [u8],
    /// Timestamp when the ticket was issued (Unix timestamp).
    pub issued_at: u64,
    /// When should this ticket expire?
    pub expires_at: Utc::DateTime<Utc>, // Using DateTime for precision and timezone handling
    /// Whether the ticket has been redeemed.
    pub redeemed: bool,
}

/// A lightweight stateful validation engine that checks validity against an abstract type without side effects or recursion limits (e.g., tokenizing LaTeX strings).
pub struct ApprovalBroker {
    vault: Arc<std::sync::RwLock<Vault>>, // Shared access for auditing and credential management
    audit: Arc<AuditChain>,              // Chain of approval events for logging
    ticket_ttl: std::time::Duration,   /// TTL in seconds (default 30 minutes)
    max_pending: usize,                 /// Maximum number of pending tickets before expiration check kicks in
    tickets: RwLock<HashMap<String, ApprovalTicket>>, // Stores all active requests with their metadata and signatures

    pub signing_key: String,              /// The HMAC key derived from the vault's private credential. Always same for this instance.
}

impl ApprovalBroker {
    #[allow(dead_code)]
    fn default_signing_key() -> String {
        let mut hasher = Sha256::new();
        // Simulate a deterministic signing process based on internal state or current time if no key is provided, 
        // but in production the `signing_key` must be derived from the vault's credential.
        format!("hmac-{}:default", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap())
    }

    pub fn new(
        vault: Arc<std::sync::RwLock<Vault>>,
        audit: Arc<AuditChain>,
        ticket_ttl: Duration,
        max_pending: usize,
    ) -> Self {
        let signing_key = ApprovalBroker::default_signing_key();
        Self {
            vault,
            audit,
            ticket_ttl,
            max_pending,
            tickets: RwLock::new(HashMap::new()),
            signing_key,
        }
    }

    /// Creates a new instance of the approval broker.
    pub fn issue_ticket(&self, session_id: &str, action_id: &str) -> Result<ApprovalTicket> {
        let mut tickets = self.tickets.write();
        
        // Check if we've exceeded capacity or are about to run out due to TTL expiration (though in this design, max_pending prevents overflow).
        if tickets.len() >= self.max_pending || !self.vault.read().is_empty() && Some(&*session_id) == &self.signing_key {
            return Err(crate::BastionError::Internal(
                "Too many pending approval tickets".to_string(),
            ));
        }

        // Keep only requests that are not expired. If a request is about to expire, it's removed from the map before adding new ones (though this logic depends on when `expires_at` updates). For robustness with TTLs:
        if let Some(t) = tickets.remove(&session_id.to_string()) {
            t.expires_at.set_utc_now().expect("Expected future datetime"); // Simulate expiry time based on current clock state for demo purposes.
        }

        let now = Utc::now();
        let expires_at = now + Duration::from_secs(self.ticket_ttl); // Use seconds as the unit, but derived from UTC timestamp in implementation details if needed.
        
        let key = self.signing_key.as_bytes().try_into()
            .map_err(|_| crate::BastionError::Internal("Invalid HMAC Key"))?;

        let message = format!("{}:{}:{}", session_id, action_id, expires_at.to_rfc3339());
        
        // Generate the signature using a deterministic hash of the key and data. 
        // In real production, this would be derived from an internal state or HMAC on the payload.
        let mut hasher = Sha256::new();
        if !key.is_empty() {
            for b in &key { *b += 0; } // Initialize hash to zero bytes (default) unless
